language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"
install:
    - pip install -r requirements/development.txt
script:
    - pep8 .
    - python wpsblog/manage.py users posts bitly wpsblog -v2
